# Generated by Django 5.0.4 on 2024-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correspondance_module',
            fields=[
                ('TRG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CASE_NUM', models.IntegerField()),
                ('TRG_STATUS', models.CharField(max_length=255)),
                ('NOTICE', models.FileField(upload_to='')),
            ],
        ),
    ]
