# Generated by Django 4.2.11 on 2024-09-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondance_module',
            name='GEN_DATE',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondance_module',
            name='CASE_NUM',
            field=models.IntegerField(unique=True),
        ),
    ]
