# Generated by Django 4.2.11 on 2024-09-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence_api', '0002_correspondance_module_gen_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondance_module',
            name='TRG_STATUS',
        ),
    ]
