# Generated by Django 5.1 on 2024-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eligibilityDetermination',
            fields=[
                ('ELIG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CASE_NUM', models.IntegerField()),
                ('PLAN_NAME', models.CharField(max_length=255)),
                ('PLAN_STATUS', models.CharField(max_length=255)),
                ('PLAN_START_DATE', models.DateField()),
                ('PLAN_END_DATE', models.DateField()),
                ('BENEFIT_AMT', models.IntegerField()),
                ('DENIAL_REASON', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
