# Generated by Django 4.2.11 on 2024-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseworkeracct',
            name='USERNAME',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
