# Generated by Django 4.2.11 on 2024-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseWorkerAcct',
            fields=[
                ('ACC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FULLNAME', models.CharField(max_length=64)),
                ('EMAIL', models.CharField(max_length=64)),
                ('PWD', models.CharField(max_length=64)),
                ('PHNO', models.IntegerField()),
                ('GENDER', models.CharField(max_length=6)),
                ('SSN', models.IntegerField()),
                ('DOB', models.DateField()),
                ('ACTIVE_SW', models.CharField(max_length=64)),
                ('CREATE_DATE', models.DateField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateField(auto_now=True)),
                ('CREATED_BY', models.CharField(max_length=64)),
                ('UPDATED_BY', models.CharField(max_length=64)),
            ],
        ),
    ]
