# Generated by Django 4.2.11 on 2024-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_alter_caseworkeracct_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseworkeracct',
            name='ACTIVE_SW',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='ACTIVE_SW',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planmaster',
            name='ACTIVE_SW',
            field=models.BooleanField(default=False),
        ),
    ]
