# Generated by Django 4.2.11 on 2024-09-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_alter_caseworkeracct_active_sw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancategory',
            name='ACTIVE_SW',
        ),
        migrations.AlterField(
            model_name='planmaster',
            name='CREATED_BY',
            field=models.CharField(default='admin', max_length=64),
        ),
        migrations.AlterField(
            model_name='planmaster',
            name='PLAN_CATEGORY_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.plancategory'),
        ),
        migrations.AlterField(
            model_name='planmaster',
            name='UPDATED_BY',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
