# Generated by Django 4.2.11 on 2024-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_remove_plancategory_active_sw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategory',
            name='CREATED_BY',
            field=models.CharField(default='admin', max_length=64),
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='UPDATED_BY',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
