# Generated by Django 4.2.11 on 2024-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_alter_plancategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmaster',
            name='PLAN_NAME',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
