# Generated by Django 4.2.11 on 2024-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('CATEGORY_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CATEGORY_NAME', models.CharField(max_length=64)),
                ('ACTIVE_SW', models.CharField(max_length=64)),
                ('CREATE_DATE', models.DateField(auto_now=True)),
                ('UPDATE_DATE', models.DateField(auto_now=True)),
                ('CREATED_BY', models.CharField(max_length=64)),
                ('UPDATED_BY', models.CharField(max_length=64)),
            ],
        ),
    ]
