# Generated by Django 4.2.11 on 2024-09-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMaster',
            fields=[
                ('PLAN_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PLAN_NAME', models.CharField(max_length=64)),
                ('PLAN_START_DATE', models.DateField()),
                ('PLAN_END_DATE', models.DateField()),
                ('PLAN_CATEGORY_ID', models.IntegerField()),
                ('ACTIVE_SW', models.CharField(max_length=64)),
                ('CREATE_DATE', models.DateField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateField(auto_now=True)),
                ('CREATED_BY', models.CharField(max_length=64)),
                ('UPDATED_BY', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='plancategory',
            name='CREATE_DATE',
            field=models.DateField(auto_now_add=True),
        ),
    ]
