# Generated by Django 4.2.11 on 2024-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_planmaster_alter_plancategory_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategory',
            name='CATEGORY_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planmaster',
            name='PLAN_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
