# Generated by Django 4.2.11 on 2024-09-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibledet_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitydetermination',
            name='BENEFIT_AMT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitydetermination',
            name='PLAN_END_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilitydetermination',
            name='PLAN_START_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
