# Generated by Django 4.2.11 on 2024-09-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibledet_api', '0002_alter_eligibilitydetermination_benefit_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitydetermination',
            name='CASE_NUM',
            field=models.IntegerField(unique=True),
        ),
    ]
