# Generated by Django 4.2.11 on 2024-09-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('CATEGORY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CATEGORY_NAME', models.CharField(max_length=64)),
                ('ACTIVE_SW', models.CharField(max_length=64)),
                ('CREATE_DATE', models.DateField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateField(auto_now=True)),
                ('CREATED_BY', models.CharField(max_length=64)),
                ('UPDATED_BY', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMaster',
            fields=[
                ('PLAN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PLAN_NAME', models.CharField(max_length=64)),
                ('PLAN_START_DATE', models.DateField()),
                ('PLAN_END_DATE', models.DateField()),
                ('PLAN_CATEGORY_ID', models.IntegerField()),
                ('ACTIVE_SW', models.CharField(max_length=64)),
                ('CREATE_DATE', models.DateField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateField(auto_now=True)),
                ('CREATED_BY', models.CharField(max_length=64)),
                ('UPDATED_BY', models.CharField(max_length=64)),
            ],
        ),
    ]
