# Generated by Django 5.0.4 on 2024-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appReg_Module',
            fields=[
                ('APP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FULLNAME', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(max_length=255)),
                ('PHNO', models.BigIntegerField()),
                ('SSN', models.BigIntegerField(unique=True)),
                ('GENDER', models.CharField(max_length=255)),
                ('STATE_NAME', models.CharField(max_length=255)),
                ('CREATE_DATE', models.DateField(auto_now=True)),
                ('UPDATE_DATE', models.DateField(auto_now_add=True)),
                ('CREATED_BY', models.CharField(max_length=255)),
                ('UPDATED_BY', models.CharField(max_length=255)),
            ],
        ),
    ]
