# Generated by Django 4.2.11 on 2024-09-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appReg_Module',
            new_name='AppReg',
        ),
    ]
