# Generated by Django 4.2.11 on 2024-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_api', '0002_rename_appreg_module_appreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreg',
            name='CASE_NUM',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='appreg',
            name='CREATED_BY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appreg',
            name='UPDATED_BY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
