# Generated by Django 4.2.11 on 2024-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_api', '0003_appreg_case_num_alter_appreg_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreg',
            name='CASE_NUM',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
