# Generated by Django 4.2.11 on 2024-09-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_api', '0006_appreg_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreg',
            name='AGE',
            field=models.DateField(null=True),
        ),
    ]
