# Generated by Django 4.2.11 on 2024-09-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_api', '0007_alter_appreg_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appreg',
            old_name='AGE',
            new_name='DOB',
        ),
    ]
