# Generated by Django 4.2.11 on 2024-09-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DC_Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CASE_NUM', models.CharField(blank=True, max_length=6, null=True)),
                ('APP_ID', models.CharField(max_length=6)),
                ('PLAN_ID', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Dc_case',
                'verbose_name_plural': 'Dc_cases',
            },
        ),
        migrations.CreateModel(
            name='DC_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_INCOME', models.CharField(max_length=6)),
                ('PROPERTY_INCOME', models.CharField(max_length=6)),
                ('CASE_NUM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacol_api.dc_cases')),
            ],
            options={
                'verbose_name': 'Dc_income',
                'verbose_name_plural': 'Dc_income',
            },
        ),
    ]
