# Generated by Django 4.2.11 on 2024-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacol_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_cases',
            name='CASE_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dc_income',
            name='INCOME_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
