# Generated by Django 4.2.11 on 2024-09-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacol_api', '0002_alter_dc_cases_case_id_alter_dc_income_income_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dc_childrens',
            options={'verbose_name': 'Dc_children', 'verbose_name_plural': 'Dc_childrens'},
        ),
        migrations.AlterModelOptions(
            name='dc_education',
            options={'verbose_name': 'Dc_education', 'verbose_name_plural': 'Dc_education'},
        ),
    ]
