# Generated by Django 4.2.11 on 2024-09-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacol_api', '0004_alter_dc_childrens_children_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_income',
            name='CASE_NUM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datacol_api.dc_cases'),
        ),
    ]
