# Generated by Django 4.2.11 on 2024-09-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_alter_planmaster_plan_name'),
        ('datacol_api', '0005_alter_dc_income_case_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dc_cases',
            name='PLAN_ID',
        ),
        migrations.AddField(
            model_name='dc_cases',
            name='PLAN_NAME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_api.planmaster', to_field='PLAN_NAME'),
        ),
    ]
