# Generated by Django 4.2.11 on 2024-09-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_api', '0005_alter_appreg_case_num'),
        ('datacol_api', '0006_remove_dc_cases_plan_id_dc_cases_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_income',
            name='CASE_NUM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appreg_api.appreg', to_field='CASE_NUM'),
        ),
    ]
