# Generated by Django 4.2.11 on 2024-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacol_api', '0010_alter_dc_childrens_case_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_cases',
            name='APP_ID',
            field=models.IntegerField(max_length=225),
        ),
        migrations.AlterField(
            model_name='dc_education',
            name='GRADUATION_YEAR',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dc_income',
            name='EMP_INCOME',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='dc_income',
            name='PROPERTY_INCOME',
            field=models.IntegerField(max_length=6),
        ),
    ]
