# Generated by Django 4.2.11 on 2024-09-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacol_api', '0011_alter_dc_cases_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc_cases',
            name='APP_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dc_income',
            name='PROPERTY_INCOME',
            field=models.IntegerField(),
        ),
    ]
